-- Insert default chatbot responses with bilingual content
INSERT INTO public.chatbot_responses (question_en, question_ar, answer_en, answer_ar, keywords, is_active) VALUES
('What services do you offer?', 'ما هي الخدمات التي تقدمونها؟', 'We offer comprehensive Odoo ERP implementation, customization, training, and support services. Our expertise covers all Odoo modules including Sales, CRM, Inventory, Accounting, HR, and Manufacturing.', 'نقدم خدمات شاملة لتطبيق وتخصيص وتدريب ودعم نظام Odoo ERP. تشمل خبرتنا جميع وحدات Odoo بما في ذلك المبيعات وإدارة علاقات العملاء والمخزون والمحاسبة والموارد البشرية والتصنيع.', ARRAY['services', 'offer', 'provide', 'خدمات', 'نقدم'], true),
('How can I contact you?', 'كيف يمكنني التواصل معكم؟', 'You can reach us through our contact form on the website, email us at info@example.com, or call us during business hours. We also offer WhatsApp support for quick inquiries.', 'يمكنك التواصل معنا من خلال نموذج الاتصال على الموقع، أو مراسلتنا عبر البريد الإلكتروني، أو الاتصال بنا خلال ساعات العمل. نقدم أيضًا دعمًا عبر واتساب للاستفسارات السريعة.', ARRAY['contact', 'reach', 'call', 'email', 'تواصل', 'اتصال'], true),
('What is Odoo?', 'ما هو أودو؟', 'Odoo is a comprehensive open-source ERP system that integrates all business operations including CRM, Sales, Inventory, Accounting, HR, Manufacturing, and more into one unified platform.', 'أودو هو نظام ERP مفتوح المصدر شامل يدمج جميع عمليات الأعمال بما في ذلك إدارة علاقات العملاء والمبيعات والمخزون والمحاسبة والموارد البشرية والتصنيع والمزيد في منصة واحدة موحدة.', ARRAY['odoo', 'erp', 'what is', 'أودو', 'ما هو'], true),
('How long does implementation take?', 'كم تستغرق عملية التنفيذ؟', 'Implementation time varies based on project scope and complexity. A basic setup can take 2-4 weeks, while comprehensive enterprise implementations may take 2-6 months. We provide detailed timelines during consultation.', 'يختلف وقت التنفيذ بناءً على نطاق المشروع وتعقيده. يمكن أن يستغرق الإعداد الأساسي 2-4 أسابيع، بينما قد تستغرق عمليات التنفيذ المؤسسية الشاملة 2-6 أشهر. نقدم جداول زمنية مفصلة خلال الاستشارة.', ARRAY['time', 'duration', 'long', 'implementation', 'وقت', 'مدة', 'تنفيذ'], true),
('Do you provide training?', 'هل توفرون التدريب؟', 'Yes, we provide comprehensive training programs for all Odoo modules. Our training includes hands-on sessions, documentation, and ongoing support to ensure your team can effectively use the system.', 'نعم، نقدم برامج تدريبية شاملة لجميع وحدات أودو. يتضمن تدريبنا جلسات عملية ووثائق ودعم مستمر لضمان قدرة فريقك على استخدام النظام بفعالية.', ARRAY['training', 'learn', 'teach', 'تدريب', 'تعلم'], true),
('What is the pricing?', 'ما هي الأسعار؟', 'Our pricing is customized based on your specific requirements, number of users, and modules needed. Contact us for a free consultation and detailed quote tailored to your business needs.', 'أسعارنا مخصصة بناءً على متطلباتك المحددة وعدد المستخدمين والوحدات المطلوبة. تواصل معنا للحصول على استشارة مجانية وعرض أسعار مفصل يناسب احتياجات عملك.', ARRAY['price', 'cost', 'pricing', 'سعر', 'تكلفة', 'أسعار'], true),
('Do you offer support after implementation?', 'هل تقدمون الدعم بعد التنفيذ؟', 'Absolutely! We offer ongoing support and maintenance packages including bug fixes, updates, user assistance, and system optimization. Our support team is available to help you get the most out of your Odoo system.', 'بالتأكيد! نقدم حزم الدعم والصيانة المستمرة بما في ذلك إصلاح الأخطاء والتحديثات ومساعدة المستخدمين وتحسين النظام. فريق الدعم لدينا متاح لمساعدتك في الحصول على أقصى استفادة من نظام أودو الخاص بك.', ARRAY['support', 'maintenance', 'help', 'دعم', 'صيانة', 'مساعدة'], true),
('Can Odoo be customized?', 'هل يمكن تخصيص أودو؟', 'Yes, Odoo is highly customizable. We can develop custom modules, modify existing features, create custom reports, and integrate with third-party systems to match your exact business processes.', 'نعم، أودو قابل للتخصيص بدرجة عالية. يمكننا تطوير وحدات مخصصة وتعديل الميزات الحالية وإنشاء تقارير مخصصة والتكامل مع أنظمة الطرف الثالث لتتناسب مع عمليات عملك بالضبط.', ARRAY['customize', 'custom', 'modify', 'تخصيص', 'تعديل'], true);
