-- Insert default services
INSERT INTO public.services (title_en, title_ar, category_en, category_ar, details_en, details_ar, image, price, duration, is_active, is_featured) VALUES
('Odoo Implementation', 'تطبيق أودو', 'ERP Solutions', 'حلول تخطيط موارد المؤسسات', 'Complete Odoo ERP implementation including modules customization, data migration, and user training.', 'تطبيق شامل لنظام أودو يشمل تخصيص الوحدات، ترحيل البيانات، وتدريب المستخدمين.', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800', 5000, '2-3 months', true, true),
('Custom Web Development', 'تطوير مواقع مخصصة', 'Web Development', 'تطوير الويب', 'Build responsive, modern web applications using React, TypeScript, and Tailwind CSS.', 'بناء تطبيقات ويب حديثة ومتجاوبة باستخدام React و TypeScript و Tailwind CSS.', 'https://images.unsplash.com/photo-1487014679447-9f8336841d58?auto=format&fit=crop&w=800', 3000, '1-2 months', true, true),
('Business Consultation', 'الاستشارات التجارية', 'Consulting', 'الاستشارات', 'Strategic IT consulting to help businesses optimize their digital transformation journey.', 'استشارات تقنية استراتيجية لمساعدة الشركات على تحسين رحلة التحول الرقمي.', 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=800', 1500, '1 month', true, false);

-- Insert default projects
INSERT INTO public.projects (title_en, title_ar, category_en, category_ar, description_en, description_ar, client_name, images, technologies, completion_date, cost, is_active, is_featured) VALUES
('Manufacturing ERP System', 'نظام تخطيط موارد التصنيع', 'Odoo', 'أودو', 'Deployed complete Odoo Manufacturing suite for a Saudi factory with inventory, MRP, and accounting integration.', 'تم نشر مجموعة أودو للتصنيع الكاملة لمصنع سعودي مع تكامل المخزون والتخطيط والمحاسبة.', 'Saudi Manufacturing Co.', ARRAY['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800'], ARRAY['Python', 'PostgreSQL', 'Odoo'], '2024-01-15', '$3500', true, true),
('School Management Platform', 'منصة إدارة المدارس', 'Web Development', 'تطوير الويب', 'Multilingual school management system with attendance tracking, grades, and parent communication.', 'نظام إدارة مدارس متعدد اللغات مع تتبع الحضور والدرجات والتواصل مع أولياء الأمور.', 'ABC International School', ARRAY['https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800'], ARRAY['React', 'TypeScript', 'Supabase'], '2024-02-20', '$2800', true, true);

-- Insert default FAQs
INSERT INTO public.faqs (question_en, question_ar, answer_en, answer_ar, category_en, category_ar, is_active, sort_order) VALUES
('What is Odoo ERP?', 'ما هو نظام أودو؟', 'Odoo is an open-source ERP system that helps businesses manage operations including sales, inventory, accounting, HR, and more.', 'أودو هو نظام تخطيط موارد المؤسسات مفتوح المصدر يساعد الشركات على إدارة العمليات بما في ذلك المبيعات والمخزون والمحاسبة والموارد البشرية والمزيد.', 'General', 'عام', true, 1),
('How long does implementation take?', 'كم تستغرق عملية التطبيق؟', 'Implementation typically takes 2-4 months depending on the complexity and number of modules required.', 'عادة ما يستغرق التطبيق من 2 إلى 4 أشهر حسب التعقيد وعدد الوحدات المطلوبة.', 'Implementation', 'التطبيق', true, 2),
('Do you provide training?', 'هل تقدمون التدريب؟', 'Yes, we provide comprehensive training for administrators and end-users as part of our implementation service.', 'نعم، نقدم تدريبًا شاملاً للمسؤولين والمستخدمين النهائيين كجزء من خدمة التطبيق.', 'Support', 'الدعم', true, 3);

-- Insert default learn resources
INSERT INTO public.learn_resources (title_en, title_ar, category_en, category_ar, main_header_en, main_header_ar, contents_en, contents_ar, author_en, author_ar, image, published_date, is_active) VALUES
('Getting Started with Odoo', 'البدء مع أودو', 'Tutorials', 'دروس تعليمية', 'Introduction to Odoo ERP', 'مقدمة لنظام أودو', 'Learn the basics of Odoo ERP system, including navigation, module overview, and initial setup. This comprehensive guide covers everything you need to know to start your Odoo journey.', 'تعلم أساسيات نظام أودو، بما في ذلك التنقل ونظرة عامة على الوحدات والإعداد الأولي. يغطي هذا الدليل الشامل كل ما تحتاج لمعرفته لبدء رحلتك مع أودو.', 'Admin Team', 'فريق الإدارة', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800', '2024-01-10', true),
('Web Development Best Practices', 'أفضل ممارسات تطوير الويب', 'Development', 'التطوير', 'Modern Web Development', 'تطوير الويب الحديث', 'Explore best practices for modern web development including responsive design, performance optimization, and accessibility standards.', 'استكشف أفضل الممارسات لتطوير الويب الحديث بما في ذلك التصميم المتجاوب وتحسين الأداء ومعايير إمكانية الوصول.', 'Admin Team', 'فريق الإدارة', 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800', '2024-01-15', true);

-- Insert default blogs
INSERT INTO public.blogs (title_en, title_ar, category_en, category_ar, content_en, content_ar, excerpt_en, excerpt_ar, slug, image, tags, is_published, is_featured, published_at) VALUES
('Why Your Business Needs an ERP System', 'لماذا تحتاج شركتك إلى نظام ERP', 'Business', 'الأعمال', 'In today''s competitive business landscape, having an integrated system to manage your operations is crucial. An ERP system brings together all aspects of your business - from inventory and sales to accounting and HR - into one unified platform. This integration eliminates data silos, reduces manual work, and provides real-time insights for better decision-making.', 'في بيئة الأعمال التنافسية اليوم، من الضروري أن يكون لديك نظام متكامل لإدارة عملياتك. يجمع نظام ERP جميع جوانب عملك - من المخزون والمبيعات إلى المحاسبة والموارد البشرية - في منصة موحدة. يلغي هذا التكامل صوامع البيانات ويقلل من العمل اليدوي ويوفر رؤى في الوقت الفعلي لاتخاذ قرارات أفضل.', 'Discover how ERP systems can transform your business operations and drive growth.', 'اكتشف كيف يمكن لأنظمة ERP تحويل عمليات عملك ودفع النمو.', 'why-your-business-needs-erp', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800', ARRAY['ERP', 'Business', 'Digital Transformation'], true, true, NOW()),
('Top 5 Web Development Trends in 2024', 'أهم 5 اتجاهات في تطوير الويب لعام 2024', 'Technology', 'التكنولوجيا', 'The web development landscape is constantly evolving. Here are the top trends shaping 2024: 1) AI-powered development tools, 2) Progressive Web Apps (PWAs), 3) Serverless architecture, 4) WebAssembly for high-performance applications, and 5) Enhanced focus on accessibility and user experience. Stay ahead by embracing these trends.', 'مشهد تطوير الويب يتطور باستمرار. إليك أهم الاتجاهات التي تشكل عام 2024: 1) أدوات التطوير المدعومة بالذكاء الاصطناعي، 2) تطبيقات الويب التقدمية (PWAs)، 3) البنية بدون خادم، 4) WebAssembly للتطبيقات عالية الأداء، و 5) التركيز المعزز على إمكانية الوصول وتجربة المستخدم.', 'Stay updated with the latest trends in web development for 2024.', 'ابق على اطلاع بأحدث الاتجاهات في تطوير الويب لعام 2024.', 'web-development-trends-2024', 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800', ARRAY['Web Development', 'Trends', 'Technology'], true, false, NOW());